name: Example workflow using Snyk

on: push
jobs:

  security:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - uses: actions/checkout@v4
        with:
            token: ${{ secrets.PAT }}

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
